"""
FULL PROJECT PIPELINE
=====================
"Understanding Pro-Environmental Behaviour Among the Youth" — Delhi study

Layer A (OPEN SOURCE / public data): real pollution & emissions data from the
   free World Bank API (no key needed). Plus an indicative state-level PM2.5
   lookup used to assign each respondent's "home-environment" pollution.

Layer B (SURVEY): 35 Delhi students (20 Delhi natives + 15 from other states),
   generated by generate_survey.py (replace with your real Google Form export).

The pipeline:
   1. Pull Layer A (World Bank) -> charts of pollution context.
   2. Load Layer B (survey), compute concern / intention / action / gap.
   3. JOIN the two layers (per-respondent home-state PM2.5).
   4. Statistics: group means, t-test (migrant vs native), correlation,
      simple regression (action ~ concern + intention + pollution).
   5. Save figures + a results table.

Run:  python3 analysis.py
"""

import os
import json
import urllib.request

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

OUT = "outputs"
os.makedirs(OUT, exist_ok=True)
sns.set_theme(style="whitegrid")

# ==========================================================================
# LAYER A  -- OPEN-SOURCE PUBLIC DATA (World Bank, no key) ----------------
# ==========================================================================
def worldbank(indicator, country="IN", start=1990, end=2024):
    url = (f"https://api.worldbank.org/v2/country/{country}/indicator/{indicator}"
           f"?format=json&per_page=200&date={start}:{end}")
    with urllib.request.urlopen(url, timeout=30) as r:
        data = json.loads(r.read().decode())
    if not isinstance(data, list) or len(data) < 2:
        return pd.Series(dtype=float)
    out = {int(e["date"]): e["value"] for e in (data[1] or []) if e.get("value") is not None}
    return pd.Series(out, dtype=float)


def layerA():
    print("[Layer A] Pulling real World Bank open data for India...")
    ind = {  # live indicator codes (verified 2026)
        "pm25":      "EN.ATM.PM25.MC.M3",
        "co2_pc":    "EN.GHG.CO2.PC.CE.AR5",
        "forest":    "AG.LND.FRST.ZS",
        "gdp_pc":    "NY.GDP.PCAP.CD",
        "pop":       "SP.POP.TOTL",
    }
    ser = {k: worldbank(v) for k, v in ind.items()}
    df = pd.DataFrame(ser).sort_index()
    df = df[df.index <= 2024]
    os.makedirs("data", exist_ok=True)
    df.to_csv("data/data_layerA_india.csv")
    print(f"   -> India {len(df)} years (1990-{int(df.index.max())})")

    # Chart 1: India PM2.5 + CO2 per capita over time
    fig, ax1 = plt.subplots(figsize=(9, 5))
    ax1.plot(df.index, df["pm25"], color="#c0392b", marker="o", ms=3, label="PM2.5 (µg/m³)")
    ax1.set_ylabel("PM2.5 mean exposure (µg/m³)", color="#c0392b")
    ax1.tick_params(axis="y", colors="#c0392b")
    ax2 = ax1.twinx()
    ax2.plot(df.index, df["co2_pc"], color="#2e7d32", marker="s", ms=3, label="CO₂/capita (t)")
    ax2.set_ylabel("CO₂ per capita (t CO₂e)", color="#2e7d32")
    ax2.tick_params(axis="y", colors="#2e7d32")
    ax1.set_title("India: ambient PM2.5 vs per-capita CO₂ (World Bank / open data)")
    ax1.set_xlabel("Year")
    fig.tight_layout(); fig.savefig(f"{OUT}/fig_A_india_trends.png", dpi=130); plt.close(fig)
    return df


# ==========================================================================
# LAYER B  -- SURVEY DATA --------------------------------------------------
# ==========================================================================
def layerB():
    print("\n[Layer B] Loading survey (35 Delhi students)...")
    df = pd.read_csv("data/survey_data.csv")
    return df


# ==========================================================================
# JOIN + STATISTICS --------------------------------------------------------
# ==========================================================================
def analyse(survey):
    print("\n[Analysis] Joining layers and testing hypotheses...")
    # per-respondent home-environment pollution is already in survey (state_pm25)

    # 1) Group comparison: Delhi natives vs migrants from other states
    groups = {}
    for mig, label in [(0, "Delhi natives (n=20)"), (1, "Migrants from other states (n=15)")]:
        g = survey[survey.is_migrant == mig]
        groups[label] = {
            "n": len(g),
            "concern": g["concern"].mean(),
            "intention": g["intention"].mean(),
            "action": g["action_score"].mean(),
            "gap": g["gap"].mean(),
        }
    grp = pd.DataFrame(groups).T.round(2)
    grp.to_csv(f"{OUT}/results_group_means.csv")
    print(grp)

    # 2) t-test: migrant vs native on concern and action
    tt = {}
    for col in ["concern", "intention", "action_score", "gap"]:
        a = survey[survey.is_migrant == 0][col]
        b = survey[survey.is_migrant == 1][col]
        t, p = stats.ttest_ind(a, b, equal_var=False)
        tt[col] = {"t": round(t, 3), "p": round(p, 3),
                   "sig_05": "yes" if p < 0.05 else "no"}
    ttest = pd.DataFrame(tt).T
    ttest.to_csv(f"{OUT}/results_ttest.csv")
    print("\n=== t-test (migrant vs native) ===")
    print(ttest)

    # 3) Correlation: concern ~ action ; intention ~ action ; pollution ~ concern
    corr = {}
    for x, y in [("concern", "action_score"), ("intention", "action_score"),
                 ("state_pm25", "concern"), ("state_pm25", "action_score")]:
        r, p = stats.pearsonr(survey[x], survey[y])
        corr[f"{x} vs {y}"] = {"r": round(r, 3), "p": round(p, 3)}
    corrdf = pd.DataFrame(corr).T
    corrdf.to_csv(f"{OUT}/results_correlations.csv")
    print("\n=== Correlations ===")
    print(corrdf)

    # 4) Regression: action ~ concern + intention + home-state PM2.5
    X = np.column_stack([np.ones(len(survey)), survey["concern"],
                         survey["intention"], survey["state_pm25"]])
    y = survey["action_score"].values.astype(float)
    # handle the NA-features: use intention & concern (all present)
    X = np.column_stack([np.ones(len(survey)), survey["concern"], survey["intention"]])
    beta, *_ = np.linalg.lstsq(X, y, rcond=None)
    yhat = X @ beta
    ss_res = np.sum((y - yhat) ** 2); ss_tot = np.sum((y - y.mean()) ** 2)
    r2 = 1 - ss_res / ss_tot
    reg = pd.DataFrame({"coef_Intercept": beta[0], "coef_concern": beta[1],
                        "coef_intention": beta[2], "R2": r2}, index=[0]).round(3)
    reg.to_csv(f"{OUT}/results_regression.csv")
    print("\n=== Simple regression (action ~ concern + intention) ===")
    print(reg)

    return survey, grp


# ==========================================================================
# CHARTS -------------------------------------------------------------
# ==========================================================================
def charts(survey):
    # Chart 1: concern vs action scatter, colored by migrant status
    fig, ax = plt.subplots(figsize=(8, 5))
    sns.scatterplot(data=survey, x="concern", y="action_score",
                    hue="is_migrant", palette={0: "#2e7d32", 1: "#c0392b"},
                    s=90, alpha=0.85, ax=ax)
    ax.set_title("Concern vs actual pro-environmental action (35 Delhi students)")
    ax.set_xlabel("Concern score (1–5)"); ax.set_ylabel("Action score (0–5)")
    h, l = ax.get_legend_handles_labels()
    ax.legend(h, ["Delhi natives", "Migrants (other states)"], title="")
    fig.tight_layout(); fig.savefig(f"{OUT}/fig1_concern_vs_action.png", dpi=130); plt.close(fig)

    # Chart 2: intention-behaviour gap per respondent
    fig, ax = plt.subplots(figsize=(9, 5))
    survey_sorted = survey.sort_values("gap")
    colors = ["#c0392b" if g > 1 else ("#f39c12" if g > 0 else "#2e7d32")
              for g in survey_sorted["gap"]]
    ax.bar(survey_sorted["respondent_id"], survey_sorted["gap"], color=colors)
    ax.axhline(0, color="k", lw=1)
    ax.set_title("Intention–behaviour gap (>0 = says they care but act less)")
    ax.set_xlabel("Respondent"); ax.set_ylabel("Gap (intention − action)")
    plt.xticks(rotation=90, fontsize=6)
    fig.tight_layout(); fig.savefig(f"{OUT}/fig2_intention_gap.png", dpi=130); plt.close(fig)

    # Chart 3: concern vs home-state PM2.5 (migrants only) + trend line
    fig, ax = plt.subplots(figsize=(8, 5))
    sns.regplot(data=survey, x="state_pm25", y="concern",
                scatter_kws={"s": 70, "alpha": 0.8}, ax=ax, color="#2e7d32")
    ax.set_title("Home-state air pollution vs environmental concern")
    ax.set_xlabel("Home-state annual mean PM2.5 (µg/m³) — indicative")
    ax.set_ylabel("Concern score (1–5)")
    fig.tight_layout(); fig.savefig(f"{OUT}/fig3_pollution_vs_concern.png", dpi=130); plt.close(fig)


def main():
    layerA_df = layerA()
    survey = layerB()
    surveyed, grp = analyse(survey)
    charts(survey)

    print("\n" + "=" * 60)
    print("FILES SAVED:")
    for f in sorted(os.listdir(OUT)):
        print("   ", f)
    print("=" * 60)


if __name__ == "__main__":
    main()
